name: ${PROJECT_NAME}
services:
  postgres:
    image: postgres:17-alpine
    container_name: ${PROJECT_NAME}-db
    restart: always
    volumes:
      - g12-data:/var/lib/postgresql/data
      - ./_entrypoint:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
    networks:
      - g12-net
  backend:
    depends_on:
      - postgres
    image: ${BACKEND_IMAGE_NAME}
    container_name: ${PROJECT_NAME}-backend
    restart: always
    networks:
      - g12-net
    environment:
      - DEPLOY_ENV=container
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_PORT=5432
      - DATABASE_HOST=${PROJECT_NAME}-db
      - DATABASE_USERNAME=${POSTGRES_APP_USER}
      - DATABASE_PASSWORD=${POSTGRES_APP_PASSWORD}
      - BACKEND_PORT=${BACKEND_PORT}
  frontend:
    depends_on:
      - backend
    image: ${FRONTEND_IMAGE_NAME}
    container_name: ${PROJECT_NAME}-frontend
    restart: always
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - g12-net
    environment:
      - NGINX_PROXY=http://${PROJECT_NAME}-backend:${BACKEND_PORT}
      - NGINX_PORT=${FRONTEND_PORT}
volumes:
  g12-data:
    name: ${PROJECT_NAME}-g12-data
networks:
  g12-net:
    name: ${PROJECT_NAME}-net